---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Install apt-transport-https
  apt:
    pkg: "apt-transport-https"
    force: yes
    state: present

- name: Add the docker PGP key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: Add the docker apt repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    update_cache: yes
    state: present

- name: Install docker-engine
  apt:
    pkg: "docker-engine"
    update_cache: yes
    state: present

- name: Install python-pip
  apt:
    pkg: "python-pip"
    state: present

- name: Install docker compose
  pip:
    name: docker-compose
    version: "1.5.2"
    state: present

- name: Install git-core
  apt:
    pkg: "git-core"
    state: present
...
