---
- name: Create user
  user:
    name: "{{ app_name }}"
    createhome: yes
    shell: /bin/bash
    generate_ssh_key: no

- name: Copy dev ssh public key
  authorized_key:
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    user: "{{ app_name }}"
    state: present

- name: Add docker group to user
  command: usermod -aG docker "{{ app_name }}"
...
